name: Manually triggered workflow

on:
  repository_dispatch:
    types: do-something

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Hello ${{ github.event.client_payload.name }}!"
